### PR TITLE
Update createOrReplaceHiveView | Closes #1

### LINKED ISSUE #1: Add createOrReplaceHiveView method
This should create or replace a Hive view from a table.

It should work for Parquet tables and Delta tables, I hope.

I tried to port over the logic from [jodie](https://github.com/MrPowers/jodie), but it's not working yet.

### PR DESCRIPTION
**Pull request by JHibbard**
Updates createOrReplaceHiveView to return Dataframe with the contents of the new Hive view, should work as expected now.

### CODE REVIEW

**Comment by MrPowers** [comment]
@brayanjuls can you please take a look at this PySpark implementation and let us know what you think?

**Comment by brayanjuls** [comment]
I think we should not return the dataframe, because:
1. the scope of the function, I would be expecting it to only create a view. 
2. I probably don't want to make an expensive full scan of the view just after creating it. Taking into account that this view could have been created from a big table.

If we want to return something it could be a boolean value to show that the view was created successfully. 

@JHibbard  - Could you please fix the unit tests for this function to make sure it works?

The initial implementation looked good probably the problem was related to the spark session not having one of these configurations, I found a similar error to this in Diane. 

`
      .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
      .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
`

**Comment by JHibbard** [comment]
Thanks for the review @brayanjuls. Returning the Dataframe wont trigger an expensive scan because it's a transformation and not an action within Spark, so it'll only be returning a reference to the view essentially. The benefit is that this would allow a more fluent API use pattern. I can definitely remove it though if you think it's confusing.

I originally added the configs to the spark context as you're outlining within the function but removed them after considering that it might be a bad idea. Eren currently has the one function, but as more functions are added, we'd have to add some code or use a decorator to add those configs to the spark context in each function. Maybe we should create a separate function that helps users set up their spark config correctly, like an `eren_init(spark)`? Alternatively we could add these details to the README.md and catch the error and refer users to the docs if they don't initialize correctly? What do you think?

**Comment by MrPowers** [comment]
I am going to merge this one and then create another PR to see if the code is runnable.  Thanks for those tips @brayanjuls.  Configuring the SparkSession correctly might have been what was tripping me up.  I thought it was a dependency thing, but it might just have been a config-thing.

**Comment by brayanjuls** [comment]
@JHibbard  - You are right, it is a transformation, and no action will get triggered. Nevertheless, I still think it would be better not to return a dataframe, because of the name of the function I see it as an output operation, not as a transformation function that will be chained with other transformations. 

Regarding the configuration in the spark context, I didn't mean to add it within the `createOrReplaceHiveView` function,  I am sorry for not putting it clearly in the previous comment. I was thinking about the sparkSession associated with the unit tests and the sparkSession associated with your test environment. I just wanted to make sure those config properties were properly set while you were doing the test. I like the idea of adding the config details in the README.md  and catching the errors.

**Pull request merged**
