### PR TITLE
Attempt to fix tests

### PR DESCRIPTION
**Pull request by MrPowers**

### CODE REVIEW

**Comment by MrPowers** [comment]
Still failing with this message:

```
~/D/c/m/eren ❯❯❯ poetry run pytest tests
=========================================== test session starts ===========================================
platform darwin -- Python 3.9.12, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/matthew.powers/Documents/code/my_apps/eren
collected 2 items                                                                                         

tests/test_public_interface.py .F                                                                   [100%]

================================================ FAILURES =================================================
______________________________________ test_createOrReplaceHiveView _______________________________________

tmp_path = PosixPath('/private/var/folders/19/_52w4zps3xjc6plz_f63j8sh0000gp/T/pytest-of-matthew.powers/pytest-1/test_createOrReplaceHiveView0')

    def test_createOrReplaceHiveView(tmp_path):
        df = spark.range(0, 5)
        path = f"{tmp_path}/some_table"
        df.write.format("delta").save(path)
>       eren.createOrReplaceHiveView("some_view", "tmp/some_table", 0)

tests/test_public_interface.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
eren/__init__.py:20: in createOrReplaceHiveView
    spark.sql(f"CREATE OR REPLACE VIEW {view_name} AS SELECT * FROM delta.`{delta_path}@v{delta_version}`")
../../../../Library/Caches/pypoetry/virtualenvs/eren-fp7L1ML9-py3.9/lib/python3.9/site-packages/pyspark/sql/session.py:1034: in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self)
../../../../Library/Caches/pypoetry/virtualenvs/eren-fp7L1ML9-py3.9/lib/python3.9/site-packages/py4j/java_gateway.py:1321: in __call__
    return_value = get_return_value(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = ('xro45', <py4j.clientserver.JavaClient object at 0x10437df40>, 'o35', 'sql'), kw = {}
converted = AnalysisException()

    def deco(*a: Any, **kw: Any) -> Any:
        try:
            return f(*a, **kw)
        except Py4JJavaError as e:
            converted = convert_exception(e.java_exception)
            if not isinstance(converted, UnknownException):
                # Hide where the exception came from that shows a non-Pythonic
                # JVM exception message.
>               raise converted from None
E               pyspark.sql.utils.AnalysisException: Unsupported data source type for direct query on files: delta; line 1 pos 50

../../../../Library/Caches/pypoetry/virtualenvs/eren-fp7L1ML9-py3.9/lib/python3.9/site-packages/pyspark/sql/utils.py:196: AnalysisException
------------------------------------------ Captured stderr call -------------------------------------------
```

**Comment by brayanjuls** [comment]
I think the problem is related to the path variable not being equal to the string "tmp/some_path", you need to specify the absolute path in the delta_path input argument. This should work,

```python
def test_createOrReplaceHiveView(tmp_path):
    df = spark.range(0, 5)
    path = f"{tmp_path}/some_table"
    df.write.format("delta").save(path)
    eren.createOrReplaceHiveView("some_view", path, 0)
    spark.sql("select * from some_view").show(truncate=False)
```

The last line is just me trying to test that it worked.

**Comment by MrPowers** [comment]
Your code worked @brayanjuls, thanks for the help.  Adding the `spark.sql("select * from some_view").show(truncate=False)` seemed to fix it magically?

**Comment by brayanjuls** [comment]
No, you can remove that line, the problem was this, "tmp/path" `eren.createOrReplaceHiveView("some_view", "tmp/path", 0)` I changed to it to this `eren.createOrReplaceHiveView("some_view", path, 0)`, now it is using the absolute path that was used to create the delta table in the first place.

**Pull request merged**
